name: 🛠️ Build Website

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      repo:
        required: true
        type: string
      continue-on-error:
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.continue-on-error }}
    permissions:
      contents: read

    steps:
      - name: Download Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.ref }}
          persist-credentials: "false"
          fetch-depth: 0
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Build Website
        run: |
          hugo

      - name: Package Website
        run: |
          tar -czf site-build.tar.gz public

      - name: Upload Site
        uses: actions/upload-artifact@v4
        with:
          name: site-build.tar.gz
          path: site-build.tar.gz
          retention-days: 1
